import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "./components/Navbar";
import Disclaimer from "./components/Disclaimer";

const oswald = Oswald({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Backstage Talks Copia Barata",
  description: "Generated by predro",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Navbar />
        {children}
        <Disclaimer />
      </body>
    </html>
  );
}
